server:
  port: ${SPRING_CLOUD_EUREKA_PORT_QA}

spring:
  application:
    name: eureka-server
  profiles:
    active: qa

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL_QA}

# logging:
#   level:
#     '[org.springframework.web]': DEBUG
#     '[com.netflix.eureka]': DEBUG
#     '[org.springframework.cloud.netflix.eureka]': DEBUG
#   pattern:
#     console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"